# Basic Exercises on Data Importing - Understanding - Manipulating - Analysis - Visualization

## Section-1: The pupose of the below exercises (1-7) is to create dictionary and convert into dataframes, how to diplay etc...
## The below exercises required to create data

### 1. Import the necessary libraries (pandas, numpy, datetime, re etc)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns
import re

# set the graphs to show in the jupyter notebook
%matplotlib inline

# set seaborn graphs to a better style
sns.set(style="ticks")

### 2. Run the below line of code to create a dictionary and this will be used for below exercises

In [2]:
raw_data = {"name": ['Bulbasaur', 'Charmander','Squirtle','Caterpie'],
            "evolution": ['Ivysaur','Charmeleon','Wartortle','Metapod'],
            "type": ['grass', 'fire', 'water', 'bug'],
            "hp": [45, 39, 44, 45],
            "pokedex": ['yes', 'no','yes','no']                        
        }

### 3. Assign it to a object called pokemon and it should be a pandas DataFrame

In [3]:
pokemon = pd.DataFrame(raw_data)
pokemon

         name   evolution   type  hp pokedex
0   Bulbasaur     Ivysaur  grass  45     yes
1  Charmander  Charmeleon   fire  39      no
2    Squirtle   Wartortle  water  44     yes
3    Caterpie     Metapod    bug  45      no

### 4. If the DataFrame columns are in alphabetical order, change the order of the columns as name, type, hp, evolution, pokedex

In [4]:
column_order = ['name', 'type', 'hp', 'evolution', 'pokedex']
pokemon = pokemon[column_order]
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

In [5]:
# Here is another and more better approach to do this. 
pokemon = pokemon.reindex(columns=column_order)
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### 5. Add another column called place, and insert places (lakes, parks, hills, forest etc) of your choice.

In [6]:
places = ['lakes', 'parks', 'hills', 'forests']
pokemon['place'] = places

pokemon

         name   type  hp   evolution pokedex    place
0   Bulbasaur  grass  45     Ivysaur     yes    lakes
1  Charmander   fire  39  Charmeleon      no    parks
2    Squirtle  water  44   Wartortle     yes    hills
3    Caterpie    bug  45     Metapod      no  forests

In [7]:
# The better approach for big projects.
pokemon.assign(place = places)

         name   type  hp   evolution pokedex    place
0   Bulbasaur  grass  45     Ivysaur     yes    lakes
1  Charmander   fire  39  Charmeleon      no    parks
2    Squirtle  water  44   Wartortle     yes    hills
3    Caterpie    bug  45     Metapod      no  forests

### 6. Display the data type of each column

In [8]:
pokemon.dtypes

name         object
type         object
hp            int64
evolution    object
pokedex      object
place        object
dtype: object

### 7. Display the info of dataframe

In [9]:
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       4 non-null      object
 1   type       4 non-null      object
 2   hp         4 non-null      int64
 3   evolution  4 non-null      object
 4   pokedex    4 non-null      object
 5   place      4 non-null      object
dtypes: int64(1), object(5)
memory usage: 324.0+ bytes

## Section-2: The pupose of the below exercise (8-20) is to understand deleting data with pandas.
## The below exercises required to use wine.data

### 8. Import the dataset *wine.txt* from the folder and assign it to a object called wine

Please note that the original data text file doesn't contain any header. Please ensure that when you import the data, you should use a suitable argument so as to avoid data getting imported as header.

In [10]:
wine = pd.read_csv('Datasets/wine.txt', header=None)
wine.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

### 9. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [11]:
""" 
The Jupyter "Re-run" Trap: You likely already ran that code cell successfully once. 
When you ran it the first time, Pandas successfully deleted those columns. 
But when you clicked "Run" a second time on the exact same cell, those columns were already long gone! 
Pandas tried to delete them again, couldn't find them, and threw a fit (KeyError).
"""
columns_to_drop = [0, 3, 6, 8, 10, 12, 13]
wine = wine.drop(columns=columns_to_drop, errors='ignore')

wine

        1     2     4    5     7     9     11
0    14.23  1.71  15.6  127  3.06  2.29  1.04
1    13.20  1.78  11.2  100  2.76  1.28  1.05
2    13.16  2.36  18.6  101  3.24  2.81  1.03
3    14.37  1.95  16.8  113  3.49  2.18  0.86
4    13.24  2.59  21.0  118  2.69  1.82  1.04
..     ...   ...   ...  ...   ...   ...   ...
173  13.71  5.65  20.5   95  0.61  1.06  0.64
174  13.40  3.91  23.0  102  0.75  1.41  0.70
175  13.27  4.28  20.0  120  0.69  1.35  0.59
176  13.17  2.59  20.0  120  0.68  1.46  0.60
177  14.13  4.10  24.5   96  0.76  1.35  0.61

[178 rows x 7 columns]

### 10. Assign the columns as below:

The attributes are (dontated by Riccardo Leardi, riclea '@' anchem.unige.it):  
1) alcohol  
2) malic_acid  
3) alcalinity_of_ash  
4) magnesium  
5) flavanoids  
6) proanthocyanins  
7) hue

In [12]:
new_column_name = ['alcohol', 'malic_acid', 'alcalinity_of_ash', 'magnesium', 'flavanoids', 'proanthocyanins', 'hue']
wine.columns = new_column_name

wine.head(4)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,14.23,1.71,15.6,127,3.06,2.29,1.04
1,13.20,1.78,11.2,100,2.76,1.28,1.05
2,13.16,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86

In [13]:
# Approach B. Specifically this approach is industry standard based. 
name_map = {1: 'alcohol', 2: 'malic_acid', 4: 'alcalinity_of_ash', 5: 'magnesium', 7: 'flavanoids', 9: 'proanthocyanins', 11: 'hue'}

wine = wine.rename(columns=name_map)

wine.head(4)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,14.23,1.71,15.6,127,3.06,2.29,1.04
1,13.20,1.78,11.2,100,2.76,1.28,1.05
2,13.16,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86

### 11. Set the values of the first 3 values from alcohol column as NaN

In [14]:
wine.loc[0:2, 'alcohol'] = np.nan
wine.head(4)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127,3.06,2.29,1.04
1,NaN,1.78,11.2,100,2.76,1.28,1.05
2,NaN,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86

In [15]:
# approach b: You can read the difference between both approaches in notion notes. 
wine.iloc[0:3, 0] = np.nan
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127,3.06,2.29,1.04
1,NaN,1.78,11.2,100,2.76,1.28,1.05
2,NaN,2.36,18.6,101,3.24,2.81,1.03
3,14.37,1.95,16.8,113,3.49,2.18,0.86
4,13.24,2.59,21.0,118,2.69,1.82,1.04

### 12. Now set the value of the rows 3 and 4 of magnesium as NaN

In [16]:
wine.loc[3:4, 'magnesium'] = np.nan
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,NaN,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,18.6,101.0,3.24,2.81,1.03
3,14.37,1.95,16.8,NaN,3.49,2.18,0.86
4,13.24,2.59,21.0,NaN,2.69,1.82,1.04

In [17]:
# This is code of checking how many nan values you have in your dataframe. 
wine.isna().sum()

alcohol              3
malic_acid           0
alcalinity_of_ash    0
magnesium            2
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### 13. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [18]:
imputation_map = {
    'alcohol': 10, 
    'magnesium': 100
}

wine = wine.fillna(value=imputation_map)
wine.head(6)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.71,15.6,127.0,3.06,2.29,1.04
1,10.00,1.78,11.2,100.0,2.76,1.28,1.05
2,10.00,2.36,18.6,101.0,3.24,2.81,1.03
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
4,13.24,2.59,21.0,100.0,2.69,1.82,1.04
5,14.20,1.76,15.2,112.0,3.39,1.97,1.05

### 14. Count the number of missing values in all columns.

In [19]:
missing_data_summary = wine.isna().sum()
print(f'Missing values headcount per column: \n\n{missing_data_summary}')

Missing values headcount per column:

alcohol              0
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### 15.  Create an array of 10 random numbers up until 10 and save it.

In [20]:
# Approach A: The modern, state-of-the-art NumPy Generator way (Best practice)
rng = np.random.default_rng(seed=42)
random_indices = rng.integers(low=0, high=10, size=10)

print(f'Random generated array: \n{random_indices}')

Random generated array:
[0 7 6 4 4 8 0 6 2 0]

In [21]:
# Approach B: The legacy NumPy way (Still widely used and perfectly fine)
np.random.seed(42)
random_indices1 = np.random.randint(0, 10, 10)

print(f'Random array generated with randint: \n{random_indices1}')

Random array generated with randint:
[6 3 7 4 6 9 2 6 7 4]

### 16.  Set the rows corresponding to the random numbers to NaN in the column *alcohol*

In [22]:
wine.loc[random_indices, 'alcohol'] =  np.nan
wine.head(10)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,10.00,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,18.6,101.0,3.24,2.81,1.03
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
4,NaN,2.59,21.0,100.0,2.69,1.82,1.04
5,14.20,1.76,15.2,112.0,3.39,1.97,1.05
6,NaN,1.87,14.6,96.0,2.52,1.98,1.02
7,NaN,2.15,17.6,121.0,2.51,1.25,1.06
8,NaN,1.64,14.0,97.0,2.98,1.98,1.08
9,13.86,1.35,16.0,98.0,3.15,1.85,1.01

### 17.  How many missing values do we have now?

In [23]:
print(f'Updated Missing values summary: \n{wine.isna().sum()}')

Updated Missing values summary:
alcohol              6
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### 18. Print only the non-null values in alcohol

In [24]:
clean_alcohol_loc = wine.loc[wine['alcohol'].notnull(), 'alcohol']
clean_alcohol_loc

1      10.00
3      14.37
5      14.20
9      13.86
10     14.10
       ...
173    13.71
174    13.40
175    13.27
176    13.17
177    14.13
Name: alcohol, Length: 172, dtype: float64

### 19. Delete the rows that contain missing values

In [25]:
# Approach B: Precision Purging using the 'subset' argument (Highly professional)
# This only drops rows if they are missing data inside the 'alcohol' column, leaving others untouched.
wine_cleaned = wine.dropna(subset=['alcohol'])
wine_cleaned

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
1,10.00,1.78,11.2,100.0,2.76,1.28,1.05
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
5,14.20,1.76,15.2,112.0,3.39,1.97,1.05
9,13.86,1.35,16.0,98.0,3.15,1.85,1.01
10,14.10,2.16,18.0,105.0,3.32,2.38,1.25
...,...,...,...,...,...,...,...
173,13.71,5.65,20.5,95.0,0.61,1.06,0.64
174,13.40,3.91,23.0,102.0,0.75,1.41,0.70
175,13.27,4.28,20.0,120.0,0.69,1.35,0.59
176,13.17,2.59,20.0,120.0,0.68,1.46,0.60
177,14.13,4.10,24.5,96.0,0.76,1.35,0.61

In [26]:
# The standard way (Drops rows with any missing values and returns a new DataFrame)
wine_cleaned2 = wine.dropna()
wine_cleaned2

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
1,10.00,1.78,11.2,100.0,2.76,1.28,1.05
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
5,14.20,1.76,15.2,112.0,3.39,1.97,1.05
9,13.86,1.35,16.0,98.0,3.15,1.85,1.01
10,14.10,2.16,18.0,105.0,3.32,2.38,1.25
...,...,...,...,...,...,...,...
173,13.71,5.65,20.5,95.0,0.61,1.06,0.64
174,13.40,3.91,23.0,102.0,0.75,1.41,0.70
175,13.27,4.28,20.0,120.0,0.69,1.35,0.59
176,13.17,2.59,20.0,120.0,0.68,1.46,0.60
177,14.13,4.10,24.5,96.0,0.76,1.35,0.61

### 20.  Reset the index, so it starts with 0 again

In [27]:
wine = wine.reset_index(drop=True)
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,1.04
1,10.00,1.78,11.2,100.0,2.76,1.28,1.05
2,NaN,2.36,18.6,101.0,3.24,2.81,1.03
3,14.37,1.95,16.8,100.0,3.49,2.18,0.86
4,NaN,2.59,21.0,100.0,2.69,1.82,1.04

## Section-3: The pupose of the below exercise (21-27) is to understand ***filtering & sorting*** data from dataframe.
## The below exercises required to use chipotle.tsv

This time we are going to pull data directly from the internet.  
Import the dataset directly from this link (https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and create dataframe called chipo

In [28]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')

chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### 21. How many products cost more than $10.00? 

Use `str` attribute to remove the $ sign and convert the column to proper numeric type data before filtering.

In [29]:
# Step 1: Clean the string and convert to float. 
chipo['item_price'] = chipo['item_price'].str.replace('$', '', regex=False).astype(float)

In [30]:
# Step 2: Drop duplicate products based on item_name and quantity (This ensure we look at the base price per unique item configuration)
chipo_unique_products = chipo.drop_duplicates(subset=['item_name', 'quantity'])

In [31]:
# Step 3: Filter for prices greater than 10.00
expensive_products = chipo_unique_products[chipo_unique_products['item_price'] > 10.00]

In [32]:
# Step 4: Count the unique item names that match this criteria
product_count = expensive_products['item_name'].nunique()

In [33]:
print(f'Number of unique products costing more than $10.00: \n=> {product_count}')

Number of unique products costing more than $10.00:
=> 28

### 22. Print the Chipo Dataframe & info about data frame

In [34]:
print("---- DATAFRAME STRUCTURAL INFO ----")
chipo.info()

print(f'\n {'=' * 122} \n')

print("---- DATAFRAME FIRST 5 ROWS ----")
chipo.head()

---- DATAFRAME STRUCTURAL INFO ----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

 ==========================================================================================================================

---- DATAFRAME FIRST 5 ROWS ----

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

### 23. What is the price of each item? 
- Delete the duplicates in item_name and quantity
- Print a data frame with only two columns `item_name` and `item_price`
- Sort the values from the most to less expensive

In [35]:
# Unique items based on item_name and quantity
unique_menu_price = chipo.drop_duplicates(subset=['item_name', 'item_price'])

In [36]:
# Print a data frame with only two columns item_name and item_price
price_lst = unique_menu_price[['item_name', 'item_price']]

In [37]:
# Sort the values from the most to less expensive
sorted_menu_price = price_lst.sort_values(by='item_price', ascending=False).reset_index(drop=True)
sorted_menu_price.head()

                      item_name  item_price
0  Chips and Fresh Tomato Salsa       44.25
1                 Carnitas Bowl       35.25
2               Chicken Burrito       35.00
3                Veggie Burrito       33.75
4                  Chicken Bowl       32.94

### 24. Sort by the name of the item

In [38]:
# Extract unique item entries cleanly using explicit projection
unique_items = chipo.drop_duplicates(subset=['item_name']).loc[:, 'item_name']


# Lexicographical sort with an explicit index reset
sorted_items = unique_items.sort_values(ascending=True).reset_index(drop=True)

sorted_items.head(10)

0        6 Pack Soft Drink
1            Barbacoa Bowl
2         Barbacoa Burrito
3    Barbacoa Crispy Tacos
4      Barbacoa Salad Bowl
5      Barbacoa Soft Tacos
6            Bottled Water
7                     Bowl
8                  Burrito
9              Canned Soda
Name: item_name, dtype: object

### 25. What was the quantity of the most expensive item ordered?

In [39]:
# Step 1: Find the exact index label or location of the maximum value in the item_price column
max_price_idx = chipo['item_price'].idxmax()

# Step 2: Use .loc to retrieve the target metrics corresponding to that index record
most_expensive_row = chipo.loc[max_price_idx, ['quantity']]

print("---- Most Expensive Item Entry ----")
most_expensive_row

---- Most Expensive Item Entry ----

quantity    15
Name: 3598, dtype: object

### 26. How many times were a Veggie Salad Bowl ordered?

In [40]:
# chipo[chipo['item_name'].str.contains('Veggie')]
veggie_salad_mask = chipo['item_name'] == 'Veggie Salad Bowl'
order_frequency = len(chipo[veggie_salad_mask].reset_index(drop=True))

order_frequency

18

### 27. How many times people orderd more than one Canned Soda?

In [41]:
# Apply compound boolean filtering with strict evaluation parentheses
soda_bulk_mask = (chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)
bulk_order_count = len(chipo[soda_bulk_mask])

bulk_order_count

20

## Section-4: The purpose of the below exercises is to understand how to perform aggregations of data frame
## The below exercises (28-33) required to use occupation.csv

###  28. Import the dataset occupation.csv and assign object as users

In [42]:
users = pd.read_csv('Datasets/occupation.csv', sep='|', index_col=False)
users = users.set_index('user_id')
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

### 29. Discover what is the mean age per occupation

In [43]:
mean_age_per_occ = users.groupby('occupation')['age'].mean()
mean_age_per_occ

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

In [44]:
# Approach B: 
# Grouping the existing 'users' dataframe by occupation and computing mean age
occupation_groups = users.groupby('occupation')

# Extracting the final combined metrics
mean_age_by_occ1 = occupation_groups['age'].mean()

### 30. Discover the Male ratio per occupation and sort it from the most to the least.

Use numpy.where() to encode gender column.

In [45]:
# Step 1: Vectorized binary encoding of the gender column
users['is_male'] = np.where(users['gender'] == 'M', 1, 0)

# Step 2: Group by occupation, compute the mean of the indicator, and sort descending
male_ratio_per_occ = users.groupby('occupation')['is_male'].mean().sort_values(ascending=False)

male_ratio_per_occ

occupation
doctor           1.000000
engineer         0.970149
technician       0.962963
retired          0.928571
programmer       0.909091
executive        0.906250
scientist        0.903226
entertainment    0.888889
lawyer           0.833333
salesman         0.750000
educator         0.726316
student          0.693878
other            0.657143
marketing        0.615385
writer           0.577778
none             0.555556
administrator    0.544304
artist           0.535714
librarian        0.431373
healthcare       0.312500
homemaker        0.142857
Name: is_male, dtype: float64

### 31. For each occupation, calculate the minimum and maximum ages

In [46]:
# Group by occupation, select the age column and compute both min and max simultaneously. 
age_extremes_per_occupation = users.groupby('occupation')['age'].agg(['min', 'max'])

age_extremes_per_occupation

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### 32. For each combination of occupation and gender, calculate the mean age

In [47]:
# Group by multiple categorical dimensions and calculate the mean of age or average age. 
multi_group_age = users.groupby(['occupation', 'gender'])['age'].mean()

multi_group_age

occupation     gender
administrator  F         40.638889
               M         37.162791
artist         F         30.307692
               M         32.333333
doctor         M         43.571429
educator       F         39.115385
               M         43.101449
engineer       F         29.500000
               M         36.600000
entertainment  F         31.000000
               M         29.000000
executive      F         44.000000
               M         38.172414
healthcare     F         39.818182
               M         45.400000
homemaker      F         34.166667
               M         23.000000
lawyer         F         39.500000
               M         36.200000
librarian      F         40.000000
               M         40.000000
marketing      F         37.200000
               M         37.875000
none           F         36.500000
               M         18.600000
other          F         35.472222
               M         34.028986
programmer     F         32.166667
               M         33.216667
retired        F         70.000000
               M         62.538462
salesman       F         27.000000
               M         38.555556
scientist      F         28.333333
               M         36.321429
student        F         20.750000
               M         22.669118
technician     F         38.000000
               M         32.961538
writer         F         37.631579
               M         35.346154
Name: age, dtype: float64

### 33.  For each occupation present the percentage of women and men

In [48]:
# Compute a row-normalized cross-tabulation and scale from decimals to percentage

gender_pct_per_occ = pd.crosstab(users['occupation'], users['gender'], normalize='index')*100

gender_pct_per_occ

gender                 F           M
occupation
administrator  45.569620   54.430380
artist         46.428571   53.571429
doctor          0.000000  100.000000
educator       27.368421   72.631579
engineer        2.985075   97.014925
entertainment  11.111111   88.888889
executive       9.375000   90.625000
healthcare     68.750000   31.250000
homemaker      85.714286   14.285714
lawyer         16.666667   83.333333
librarian      56.862745   43.137255
marketing      38.461538   61.538462
none           44.444444   55.555556
other          34.285714   65.714286
programmer      9.090909   90.909091
retired         7.142857   92.857143
salesman       25.000000   75.000000
scientist       9.677419   90.322581
student        30.612245   69.387755
technician      3.703704   96.296296
writer         42.222222   57.777778

In [49]:
gender_pct_per_occ1 = pd.crosstab(users['occupation'], users['gender'], normalize='index')*100

# Converting values into strings with a percentage sign
clean_pct_table_of_occ = gender_pct_per_occ1.map(lambda val: f'{int(val)}%') 

clean_pct_table_of_occ

gender           F     M
occupation
administrator  45%   54%
artist         46%   53%
doctor          0%  100%
educator       27%   72%
engineer        2%   97%
entertainment  11%   88%
executive       9%   90%
healthcare     68%   31%
homemaker      85%   14%
lawyer         16%   83%
librarian      56%   43%
marketing      38%   61%
none           44%   55%
other          34%   65%
programmer      9%   90%
retired         7%   92%
salesman       25%   75%
scientist       9%   90%
student        30%   69%
technician      3%   96%
writer         42%   57%

## Section-5: The purpose of the below exercises is to understand how to use lambda-apply-functions
## The below exercises (34-41) required to use student-mat.csv and student-por.csv files

### 34. Import the datasets *student-mat* and *student-por* and append them and assigned object as df

In [50]:
# Step 1: Load both independent student datasets
student_mat = pd.read_csv('Datasets/student-mat.csv')
student_por = pd.read_csv('Datasets/student-por.csv')

# Step 2: Append vertically using the modern concat engin with an index reset
df = pd.concat([student_mat, student_por], axis=0, ignore_index=True)
df.shape

(1044, 33)

### 35. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [51]:
# Slice all rows and columns from 'school' up to 'guardian' including 'guardian'
df_sliced = df.loc[:, 'school':'guardian']

# Force pandas to never wrap rows vertically
pd.set_option('display.expand_frame_repr', False)

print(df_sliced.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason guardian
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  course   mother
1     GP   F   17       U     GT3       T     1     1  at_home     other  course   father
2     GP   F   15       U     LE3       T     1     1  at_home     other   other   mother
3     GP   F   15       U     GT3       T     4     2   health  services    home   mother
4     GP   F   16       U     GT3       T     3     3    other     other    home   father

### 36. Create a lambda function that captalize strings (example: if we give at_home as input function and should give At_home as output.

In [52]:
# Define an anonymous lambda function and assign it to a variable for reuse 
capitalize_lambda = lambda x: str(x).capitalize()

test_input = 'at_home'
print(f'Input: {test_input} \nOutput: {capitalize_lambda(test_input)}')

Input: at_home
Output: At_home

### 37. Capitalize both Mjob and Fjob variables using above lamdba function

In [53]:
# Apply the lambda function to transform both columns
Mjob = df['Mjob'].apply(capitalize_lambda)
Fjob = df['Fjob'].apply(capitalize_lambda)

print(f'Capitalized Mjob: \n{Mjob.head(4)}')
print()
print(f'Capitalized Fjob: \n{Fjob.head(4)}')

Capitalized Mjob:
0    At_home
1    At_home
2    At_home
3     Health
Name: Mjob, dtype: object

Capitalized Fjob:
0     Teacher
1       Other
2       Other
3    Services
Name: Fjob, dtype: object

### 38. Print the last elements of the data set. (Last few records)

In [54]:
df.tail()

     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
1039     MS   F   19       R     GT3       T     2     3  services     other  ...      5        4      2     1     2      5        4  10  11  10
1040     MS   F   18       U     LE3       T     3     1   teacher  services  ...      4        3      4     1     1      1        4  15  15  16
1041     MS   F   18       U     GT3       T     1     1     other     other  ...      1        1      1     1     1      5        6  11  12   9
1042     MS   M   17       U     LE3       T     3     1  services  services  ...      2        4      5     3     4      2        6  10  10  10
1043     MS   M   18       R     LE3       T     3     2  services     other  ...      4        4      1     3     4      5        4  10  11  11

[5 rows x 33 columns]

### 39. Did you notice the original dataframe is still lowercase? Why is that? Fix it and captalize Mjob and Fjob.

In [55]:
df['Mjob'] = Mjob
df['Fjob'] = Fjob
df

     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0        GP   F   18       U     GT3       A     4     4   At_home   Teacher  ...      4        3      4     1     1      3        6   5   6   6
1        GP   F   17       U     GT3       T     1     1   At_home     Other  ...      5        3      3     1     1      3        4   5   5   6
2        GP   F   15       U     LE3       T     1     1   At_home     Other  ...      4        3      2     2     3      3       10   7   8  10
3        GP   F   15       U     GT3       T     4     2    Health  Services  ...      3        2      2     1     1      5        2  15  14  15
4        GP   F   16       U     GT3       T     3     3     Other     Other  ...      4        3      2     1     2      5        4   6  10  10
...     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...  ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
1039     MS   F   19       R     GT3       T     2     3  Services     Other  ...      5        4      2     1     2      5        4  10  11  10
1040     MS   F   18       U     LE3       T     3     1   Teacher  Services  ...      4        3      4     1     1      1        4  15  15  16
1041     MS   F   18       U     GT3       T     1     1     Other     Other  ...      1        1      1     1     1      5        6  11  12   9
1042     MS   M   17       U     LE3       T     3     1  Services  Services  ...      2        4      5     3     4      2        6  10  10  10
1043     MS   M   18       R     LE3       T     3     2  Services     Other  ...      4        4      1     3     4      5        4  10  11  11

[1044 rows x 33 columns]

### 40. Create a function called majority that return a boolean value to a new column called legal_drinker

In [56]:
# Step 1: Define the custom function as required 
def majority(age): 
    return age >= 18

# Step 2: Apply the function to the 'age' column and assign it to the new column
df['legal_drinker'] = df['age'].apply(majority)

df[['age', 'legal_drinker']].head()

   age  legal_drinker
0   18           True
1   17          False
2   15          False
3   15          False
4   16          False

### 41. Multiply every number of the dataset by 10.

In [57]:
# Step 1: Isolate only the numeric columns. 
numeric_sub_matrix = df.select_dtypes(include='number')

# Step 2: Multiply the entire sub-matrix by 10 
scaled_numeric_matrix = numeric_sub_matrix * 10

# Step 3: Align and assign the modified values back to the original DataFrame
df[scaled_numeric_matrix.columns] = scaled_numeric_matrix

## Section-6: The purpose of the below exercises is to understand how to perform simple joins
## The below exercises (42-48) required to use cars1.csv and cars2.csv files

### 42. Import the datasets cars1.csv and cars2.csv and assign names as cars1 and cars2

In [58]:
cars1 = pd.read_csv('Datasets/cars1.csv')
cars2 = pd.read_csv('Datasets/cars2.csv')

   ### 43. Print the information to cars1 by applying below functions 
   hint: Use different functions/methods like type(), head(), tail(), columns(), info(), dtypes(), index(), shape(), count(), size(), ndim(), axes(), describe(), memory_usage(), sort_values(), value_counts()
   Also create profile report using pandas_profiling.Profile_Report

#####  => Checking shape and Structure

In [59]:
# Check object class type
print(type(cars1))

# Get row and column counts asa tuple (Rows, Columns)
print(cars1.shape)

# Get the dimension score (Return 2 for tabular DataFrame)
print(cars1.ndim)

# Total cell count (Rows * columns)
print(cars1.size)

<class 'pandas.core.frame.DataFrame'>
(198, 14)
2
2772

##### => Schema & Memory Footprint Validation

In [60]:
# Check column label names
print(cars1.columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [61]:
# Inspect index sequence or range boundaries
print(cars1.index)

RangeIndex(start=0, stop=198, step=1)

In [62]:
# View data type assigned to each individual feature column
print(cars1.dtypes)

mpg             float64
cylinders         int64
displacement      int64
horsepower       object
weight            int64
acceleration    float64
model             int64
origin            int64
car              object
Unnamed: 9      float64
Unnamed: 10     float64
Unnamed: 11     float64
Unnamed: 12     float64
Unnamed: 13     float64
dtype: object

In [63]:
# Get the physical memory consumption per column in bytes
print(cars1.memory_usage())

Index            132
mpg             1584
cylinders       1584
displacement    1584
horsepower      1584
weight          1584
acceleration    1584
model           1584
origin          1584
car             1584
Unnamed: 9      1584
Unnamed: 10     1584
Unnamed: 11     1584
Unnamed: 12     1584
Unnamed: 13     1584
dtype: int64

In [64]:
# Full diagnostic review: Combines types, non-null counts, and memory footprint
print(cars1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           198 non-null    float64
 1   cylinders     198 non-null    int64
 2   displacement  198 non-null    int64
 3   horsepower    198 non-null    object
 4   weight        198 non-null    int64
 5   acceleration  198 non-null    float64
 6   model         198 non-null    int64
 7   origin        198 non-null    int64
 8   car           198 non-null    object
 9   Unnamed: 9    0 non-null      float64
 10  Unnamed: 10   0 non-null      float64
 11  Unnamed: 11   0 non-null      float64
 12  Unnamed: 12   0 non-null      float64
 13  Unnamed: 13   0 non-null      float64
dtypes: float64(7), int64(5), object(2)
memory usage: 21.8+ KB
None

##### => Data Content & Distribution Auditing

In [65]:
# Preview top 3 data records
cars1.head(3)

    mpg  cylinders  displacement horsepower  weight  acceleration  model  origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13
0  18.0          8           307        130    3504          12.0     70       1  chevrolet chevelle malibu         NaN          NaN          NaN          NaN          NaN
1  15.0          8           350        165    3693          11.5     70       1          buick skylark 320         NaN          NaN          NaN          NaN          NaN
2  18.0          8           318        150    3436          11.0     70       1         plymouth satellite         NaN          NaN          NaN          NaN          NaN

In [66]:
# Preview bottom 3 data records
cars1.tail(3)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  origin                 car  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13
195  29.0          4            85         52    2035          22.2     76       1  chevrolet chevette         NaN          NaN          NaN          NaN          NaN
196  24.5          4            98         60    2164          22.1     76       1     chevrolet woody         NaN          NaN          NaN          NaN          NaN
197  29.0          4            90         70    1937          14.2     76       2           vw rabbit         NaN          NaN          NaN          NaN          NaN

In [67]:
# Total count of non-missing (Valid) values per feature column
cars1.count()

mpg             198
cylinders       198
displacement    198
horsepower      198
weight          198
acceleration    198
model           198
origin          198
car             198
Unnamed: 9        0
Unnamed: 10       0
Unnamed: 11       0
Unnamed: 12       0
Unnamed: 13       0
dtype: int64

In [68]:
# Statistical overview matrix (Mean, Std Dev, Min, Max, Quantiles)
cars1.describe()

              mpg   cylinders  displacement       weight  acceleration       model      origin  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13
count  198.000000  198.000000    198.000000   198.000000    198.000000  198.000000  198.000000         0.0          0.0          0.0          0.0          0.0
mean    19.719697    5.898990    223.469697  3177.888889     15.005556   72.818182    1.439394         NaN          NaN          NaN          NaN          NaN
std      5.814254    1.785417    115.181017   934.783733      2.872382    1.865332    0.708085         NaN          NaN          NaN          NaN          NaN
min      9.000000    3.000000     68.000000  1613.000000      8.000000   70.000000    1.000000         NaN          NaN          NaN          NaN          NaN
25%     15.000000    4.000000    113.250000  2302.500000     13.000000   71.000000    1.000000         NaN          NaN          NaN          NaN          NaN
50%     19.000000    6.000000    228.000000  3030.000000     15.000000   73.000000    1.000000         NaN          NaN          NaN          NaN          NaN
75%     24.375000    8.000000    318.000000  4080.750000     16.800000   74.000000    2.000000         NaN          NaN          NaN          NaN          NaN
max     35.000000    8.000000    455.000000  5140.000000     23.500000   76.000000    3.000000         NaN          NaN          NaN          NaN          NaN

##### => Structural Reshaping & Value counts

In [69]:
# Frequency count of unique records within a specific categorical series
cars1['mpg'].value_counts()

mpg
14.0    19
18.0    16
13.0    16
15.0    15
26.0    12
16.0    11
24.0    10
25.0    10
19.0     9
23.0     8
21.0     8
22.0     8
20.0     7
29.0     6
28.0     6
12.0     6
27.0     5
31.0     4
17.0     4
11.0     4
30.0     2
10.0     2
32.0     2
9.0      1
35.0     1
33.0     1
17.5     1
15.5     1
14.5     1
22.5     1
24.5     1
Name: count, dtype: int64

In [70]:
# Sort values by a target feature column
cars1.sort_values(by='mpg', ascending=False)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  origin                  car  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13
54   35.0          4            72         69    1613          18.0     71       3          datsun 1200         NaN          NaN          NaN          NaN          NaN
181  33.0          4            91         53    1795          17.5     75       3     honda civic cvcc         NaN          NaN          NaN          NaN          NaN
131  32.0          4            71         65    1836          21.0     74       3  toyota corolla 1200         NaN          NaN          NaN          NaN          NaN
145  32.0          4            83         61    2003          19.0     74       3           datsun 710         NaN          NaN          NaN          NaN          NaN
53   31.0          4            71         65    1773          19.0     71       3  toyota corolla 1200         NaN          NaN          NaN          NaN          NaN
..    ...        ...           ...        ...     ...           ...    ...     ...                  ...         ...          ...          ...          ...          ...
103  11.0          8           400        150    4997          14.0     73       1     chevrolet impala         NaN          NaN          NaN          NaN          NaN
67   11.0          8           429        208    4633          11.0     72       1      mercury marquis         NaN          NaN          NaN          NaN          NaN
25   10.0          8           360        215    4615          14.0     70       1            ford f250         NaN          NaN          NaN          NaN          NaN
26   10.0          8           307        200    4376          15.0     70       1            chevy c20         NaN          NaN          NaN          NaN          NaN
28    9.0          8           304        193    4732          18.5     70       1             hi 1200d         NaN          NaN          NaN          NaN          NaN

[198 rows x 14 columns]

### 44. It seems our first dataset has some unnamed blank columns, fix cars1

In [71]:
cars1 = cars1.loc[:, :'car']
cars1.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car'],
      dtype='object')

### 45. What is the number of observations in each dataset?

In [72]:
rows_cars1 = cars1.shape[0]
rows_cars2 = cars2.shape[0]

print(f'Number of observations in cars1: {rows_cars1}')
print(f'Number of observations in cars2: {rows_cars2}')

Number of observations in cars1: 198
Number of observations in cars2: 200

### 46. Join cars1 and cars2 into a single DataFrame called cars

In [73]:
# Combine both DataFrames vertically along rows (axis=0)
# ignore_index=True reset the index to prevent duplicate row coordinates

cars = pd.concat([cars1, cars2], axis=0, ignore_index=True)

print(f'Shape of cars1: {cars1.shape}')
print(f'Shape of cars2: {cars2.shape}')
print(f'Shape of combined car table: {cars.shape}')

Shape of cars1: (198, 9)
Shape of cars2: (200, 9)
Shape of combined car table: (398, 9)

### 47. There is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [74]:
# Step 1: Check the total number of nows currently in the unified table 
num_observations = cars.shape[0]

# Step 2: Generate a random integer array matching the exact row count 
# Setting high to 73001 makes 73000 inclusive in the distribution 

np.random.seed(42)
synthetic_owners = np.random.randint(15000, 73001, size=num_observations)

### 48. Add the column owners to cars

In [75]:
# Step 1: Inject the array structurally as a brand-new column field 
cars['owners'] = synthetic_owners

# Step 2: Verify the feature injection worked seamlessly 
cars.head()
cars.shape

(398, 10)

## Section-7: The purpose of the below exercises is to understand how to perform date time operations

### 49. Write a Python script to display the
- a. Current date and time
- b. Current year
- c. Month of year
- d. Week number of the year
- e. Weekday of the week
- f. Day of year
- g. Day of the month
- h. Day of week

In [76]:
from datetime import datetime

# Grab the current localization date and time right now
now = datetime.now()

now

datetime.datetime(2026, 6, 15, 14, 56, 41, 678123)

In [77]:
# Current year (%Y extract the full 4-digit year)
print(f'Current year: {now.strftime('%Y')}')

Current year: 2026

In [78]:
# Month of year (%B extracts full name, %m extracts month number)
print(f'Month of year: {now.strftime('%B')} ({now.strftime('%m')})')

Month of year: June (06)

In [79]:
# Week number of the year (%U or %W calculate week number from 00 to 53)
print(f'Week number of the year: {now.strftime('%W')}')

Week number of the year: 24

In [80]:
# Weekday of the week (%A extract full day from 001 to 366)
print(f'Weekday of the week: {now.strftime('%A')}')

Weekday of the week: Monday

In [81]:
# Day of year(%j extracts the Julian day from 001 to 366)
print(f'Day of year: {now.strftime('%j')}')

Day of year: 166

In [82]:
# Day of the month (%d extracts the zero-padded day number)
print(f'Day of th month: {now.strftime('%d')}')

Day of th month: 15

In [83]:
# Day of week as a number (%w extracts day of week, where 0 is Sunday and 6 is Saturday)
print(f'Day of week (as number): {now.strftime('%w')}')

Day of week (as number): 1

### 50. Write a Python program to convert a string to datetime.
Sample String : Jul 1 2014 2:43PM 

Expected Output : 2014-07-01 14:43:00

In [84]:
# Step 1: Define a simple date string 
date_text = "Jul 1 2014 2:43PM"

# Step 2: Define the exact matching blueprint format
# %Y = 4-digit year, %m = 2-digit month, %d = 2-digit day
# %H = 24-hour clock hour, %M = minute, %S = second
str_format = "%b %d %Y %H:%M%p"

# Step 3: Parse the string into datetime object
parsed_datetime = datetime.strptime(date_text, str_format)

# Step 4: View a clean human-readable representation using strftime 
clean_output = parsed_datetime.strftime("%Y-%B-%d %I:%M")

clean_output

'2014-July-01 02:43'

### 51. Write a Python program to subtract five days from current date.

Current Date : 2015-06-22

5 days before Current Date : 2015-06-17

In [85]:
from datetime import datetime, timedelta

# Step 1: Capture the current date.
current_date = datetime.now()
print(f'Current Date: {current_date.strftime('%Y-%m-%d %H:%M:%S')}')

# Step 2: Define a duration vector of exactly 5 days.
five_day_duration = timedelta(days=5)

# Step 3: Perform subtraction to step back chronologically 
past_date = current_date - five_day_duration

print(f'Date 5 Days ago: {past_date.strftime('%Y-%m-%d')}')

Current Date: 2026-06-15 14:56:42
Date 5 Days ago: 2026-06-10

### 52. Write a Python program to convert unix timestamp string to readable date.

Sample Unix timestamp string : 1284105682
    
Expected Output : 2010-09-10 13:31:22

In [86]:
# Step 1: Given sample Unix timestamp string.
unix_str = '1284105682'

# Step 2: Convert the test string to a numerical integer.
unix_int = int(unix_str)

# Step 3: Convert the integer seconds into a structured datetime object.
readable_date = datetime.fromtimestamp(unix_int)

# Step 4: Format the object to match the Expected Output format perfectly. 
# %Y = Year, %m = Month, %d = Day, %H = Hour, %M = Minute, %S = Second
final_output = readable_date.strftime('%Y-%m-%d %H:%M:%S %p')

print(f'Expected output: {final_output}')

Expected output: 2010-09-10 13:31:22 PM

### 53. Convert the below Series to pandas datetime : 

DoB = pd.Series(["07Sep59","01Jan55","15Dec47","11Jul42"])

Make sure that the year is 19XX not 20XX

In [87]:
# Step 1: Give input Series represent Date of Birth strings
DoB = pd.Series(['07Sep59', '01Jan55', '15Dec47', '11Jul42'])

# Step 2: Modify the string in a vectorized loop to insert explicitly '19' century. 
dob_string_fixed = DoB.str[:-2] + '19' + DoB.str[-2:]

# Step 3: Convert the modified Series into structured pandas datetime elements. 
# %d = Day, %b = Short Month Name, %Y = 4-digit year 
dob_series = pd.to_datetime(dob_string_fixed, format="%d%b%Y")

print(f'Expected Output: \n\n{dob_series}')

Expected Output:

0   1959-09-07
1   1955-01-01
2   1947-12-15
3   1942-07-11
dtype: datetime64[ns]

### 54. Write a Python program to get days between two dates.

In [88]:
# Step 1: Sample start and end date boundaries
start_dates = pd.Series(["2026-01-01", "2026-05-15", "2026-10-10"])
end_dates = pd.Series(["2026-01-10", "2026-05-20", "2026-12-25"])

# Convert the text string Series to structured pandas datetime format. 
dt_start = pd.to_datetime(start_dates, format='%Y-%m-%d')
dt_end = pd.to_datetime(end_dates, format='%Y-%m-%d')

# Calculate the raw time delta duration vector
time_difference  = dt_end - dt_start

# Extract the integer days component from the structured timedelta object 
# .dt.days isolates the scalar integer of full elapsed days
final_output = time_difference.dt.days

final_output

0     9
1     5
2    76
dtype: int64

### 55. Convert the below date to datetime and then change its display format using the .dt module

Date = "15Dec1989"

Result : "Friday, 15 Dec 98"

In [89]:
# Step 1: Store sample data string within a pandas Series container.
date = pd.Series(['15Dec1989'])

# Step 2: Convert the text string to a structured datetime object. 
# %d = Day, %b = Short Month, %Y = 4-Digit Year
datetime_object = pd.to_datetime(date, format='%d%b%Y')

# Step 3: Change it's display format using the .dt module and strftime tokens
# %A = Full Weekday, %d = Day, %b = Short Month, %y = 2-Digit Year
final_output = datetime_object.dt.strftime('%A, %d-%b-%y')

print(f'Expected Output: \n\n{final_output.loc[0]}')

Expected Output:

Friday, 15-Dec-89

## The below exercises (56-66) required to use wind.data file

### About wind.data:

The data have been modified to contain some missing values, identified by NaN.  

1. The data in 'wind.data' has the following format:

"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""
The first three columns are year, month and day.  The remaining 12 columns are average windspeeds in knots at 12 locations in Ireland on that day.

### 56. Import the dataset wind.data and assign it to a variable called data and replace the first 3 columns by a proper date time index

In [2]:
# Step 1: Load the dateset using comma separation and merge the first 3 columns into a date (for merging I use parse_dates=[] parameter.)
data = pd.read_csv('Datasets/wind.data', sep=',', parse_dates=[[0, 1, 2]])

# Step 2: Rename the combined column to establish a clean primary namespace
data = data.rename(columns={'Yr_Mo_Dy': 'Date'})

# Step 3: Set the parsed date column as the official index
data = data.set_index("Date")

print(f'Expected Output Schema: \n\n{data.head()}')

C:\Users\khush\AppData\Local\Temp\ipykernel_19956\4138912907.py:2: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  data = pd.read_csv('Datasets/wind.data', sep=',', parse_dates=[[0, 1, 2]])
C:\Users\khush\AppData\Local\Temp\ipykernel_19956\4138912907.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data = pd.read_csv('Datasets/wind.data', sep=',', parse_dates=[[0, 1, 2]])

Expected Output Schema:

              RPT    VAL    ROS    KIL    SHA   BIR    DUB    CLA    MUL  \
Date
2061-01-01  15.04  14.96  13.17   9.29    NaN  9.87  13.67  10.25  10.83
2061-01-02  14.71    NaN  10.83   6.50  12.62  7.67  11.50  10.04   9.79
2061-01-03  18.50  16.88  12.33  10.13  11.17  6.17  11.25    NaN   8.50
2061-01-04  10.58   6.63  11.75   4.58   4.54  2.88   8.63   1.79   5.83
2061-01-05  13.33  13.25  11.42   6.17  10.71  8.21  11.92   6.54  10.92

              CLO    BEL    MAL
Date
2061-01-01  12.58  18.50  15.04
2061-01-02   9.67  17.54  13.83
2061-01-03   7.67  12.75  12.71
2061-01-04   5.88   5.46  10.88
2061-01-05  10.34  12.92  11.83

### 57. Year 2061 is seemingly imporoper. Convert every year which are < 70 to 19XX instead of 20XX.

In [3]:
# Step 1: Capture the current calender year from the host machine runtime. 
# This prevents hardcoding boundaries (e.g., automatically evaluates to 2026)
current_year = pd.Timestamp.now().year

# Step 2: Identify invalid dates using an index condition
safe_timeline_condition = data.index.year <= current_year 

# Step 3: Apply the vectorized shift exclusively to dates. 
# If True ( <= 2026 ): Keep value. If False ( > 2026 ): Subtract 100 years.
corrected_index = data.index.where(
    safe_timeline_condition,
    data.index - pd.DateOffset(years=100)
)

# Step 4: Assign the corrected index to the DataFrame
data.index = corrected_index

data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### 58. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [4]:
data.index.dtype

dtype('<M8[ns]')

### 59. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [5]:
# Step 1: Generate the boolean matrix and collapse it column-wise to get missing counts.
missing_values_per_location = data.isna().sum()

# Step 2: Display the resulting frequency Series. 
print(f'=> Missing Value Counts Per Location: \n\n{missing_values_per_location}')

=> Missing Value Counts Per Location:

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### 60. Compute how many non-missing values there are in total.

In [6]:
# Step 1: Total matrix capacity minus total null count (Fastest O(1) space allocation)
total_cells = data.size
total_missing = data.isna().sum().sum()


# Step 2: Compute the scaler total of valid entries
total_non_missing = total_cells - total_missing

print(f'=> Total Non-Missing Values across dataset: \n{total_non_missing}')

=> Total Non-Missing Values across dataset:
78857

### 61. Calculate the mean windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [7]:
# Step 1: Compress the 2D matrix into a 1D vector, dropping null values automatically 
flattened_series = data.stack()

# Step 2: Calculate the un-biased global mean from the flattened array. 
grand_mean = flattened_series.mean()

In [8]:
# Approach B
# Flawed method: Average of column means applies equal weight to unequal columns
biased_mean = data.mean().mean()

In [9]:
print(f'True Grand Mean (Stacked): {grand_mean:.4f}')
print(f'Biased Shortcut (Mean of Means): {biased_mean:.4f}')
print(f'Absolute Bias Distortion Error: {abs(grand_mean - biased_mean):.9f}')

True Grand Mean (Stacked): 10.2279
Biased Shortcut (Mean of Means): 10.2280
Absolute Bias Distortion Error: 0.000098597

### 62. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [10]:
# Step 1: Execute multi-aggregation across rows (axis=0) and transpose (.T) the matrix. 
loc_stats = data.agg(['min', 'max', 'mean', 'std']).T

print(f"Expected Output (loc_stats Schema):\n\n{loc_stats.head()}")

Expected Output (loc_stats Schema):

      min    max       mean       std
RPT  0.67  35.80  12.362987  5.618413
VAL  0.21  33.37  10.644314  5.267356
ROS  1.50  33.84  11.660526  5.008450
KIL  0.00  28.46   6.306468  3.605811
SHA  0.13  37.54  10.455834  4.936125

### 63. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [11]:
day_stats = data.agg(['min', 'max', 'mean', 'std'], axis=1)

day_stats

             min    max       mean       std
Date
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356
...          ...    ...        ...       ...
1978-12-27  8.08  40.08  16.708333  7.868076
1978-12-28  5.00  41.46  15.150000  9.687857
1978-12-29  8.71  29.58  14.890000  5.756836
1978-12-30  9.13  28.79  15.367500  5.540437
1978-12-31  9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

### 64. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [12]:
# Step 1: Generate a vectorized boolean mask targeting the January integer flag (1)
january_mask = data.index.month == 1

# Step 2: Slice the matrix using the mask and compute the arithmetic mean column-wise
jan_mean_windspeed = data[january_mask].mean()

print(f'January Average windspeed per location: \n\n{jan_mean_windspeed}')

January Average windspeed per location:

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### 65. Calculate the mean windspeed for each month in the dataset.  
#### Treat January 1961 and January 1962 as *different* months.
#### (hint: first find a  way to create an identifier unique for each month.)

In [14]:
# Step 1: Generate a unique month-year interval identifier (PeriodIndex)
unique_month_identifier = data.index.to_period('M')

# Step 2: Group by the periods and calculate the arithmetic mean column-wise
monthly_mean_speeds = data.groupby(unique_month_identifier).mean()

print(f'Monthly Mean Windspeed Matrix: \n\n{monthly_mean_speeds.head()}')

Monthly Mean Windspeed Matrix:

               RPT        VAL        ROS       KIL        SHA        BIR  \
Date
1961-01  14.841333  11.988333  13.431613  7.736774  11.072759   8.588065
1961-02  16.269286  14.975357  14.441481  9.230741  13.852143  10.937500
1961-03  10.890000  11.296452  10.752903  7.284000  10.509355   8.866774
1961-04  10.722667   9.427667   9.998000  5.830667   8.435000   6.495000
1961-05   9.860968   8.850000  10.818065  5.905333   9.490323   6.574839

               DUB        CLA        MUL        CLO        BEL        MAL
Date
1961-01  11.184839   9.245333   9.085806  10.107419  13.880968  14.703226
1961-02  11.890714  11.846071  11.821429  12.714286  18.583214  15.411786
1961-03   9.644194   9.829677  10.294138  11.251935  16.410968  15.720000
1961-04   6.925333   7.094667   7.342333   7.237000  11.147333  10.278333
1961-05   7.604000   8.177097   8.039355   8.499355  11.900323  12.011613

### 66. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [16]:
# Step 1: Filter chronological horizon starting exactly on Monday, Jan 2, 1961.
df_sliced = data.loc["1961-01-02" : ]

# Step 2: Use .resample('7D') to create continuous 7-day windows and flatten cells via .stack()
day_stats_global = df_sliced.resample('7D').apply(
    lambda window: pd.Series(
        {
            "min": window.stack().min(), 
            "max": window.stack().max(), 
            "mean": window.stack().mean(),
            "std": window.stack().std(),
        }
    )
)

# Step 3: Extract exactly the first 52 weeks of the operation
first_52_weeks_global = day_stats_global.head(52)

first_52_weeks_global.head()

             min    max       mean       std
Date
1961-01-02  1.79  18.50   9.867073  3.492885
1961-01-09  0.50  20.71   8.353214  4.637544
1961-01-16  1.04  20.79   9.373253  4.704363
1961-01-23  6.04  27.71  16.922892  5.061242
1961-01-30  3.63  24.21  11.800357  4.376350

## The below exercises (67-70) required to use appl_1980_2014.csv  file

### 67. Import the file appl_1980_2014.csv and assign it to a variable called 'apple'

### 68.  Check out the type of the columns

### 69. Transform the Date column as a datetime type

### 70.  Set the date as the index

### 71.  Is there any duplicate dates?

### 72.  The index is from the most recent date. Sort the data so that the first entry is the oldest date.

### 73. Get the last business day of each month

### 74.  What is the difference in days between the first day and the oldest

### 75.  How many months in the data we have?

## Section-8: The purpose of the below exercises is to understand how to create basic graphs

### 76. Plot the 'Adj Close' value. Set the size of the figure to 13.5 x 9 inches

## The below exercises (77-80) required to use Online_Retail.csv file

### 77. Import the dataset from this Online_Retail.csv and assign it to a variable called online_rt

### 78. Create a barchart with the 10 countries that have the most 'Quantity' ordered except UK

### 79.  Exclude negative Quatity entries

### 80. Create a scatterplot with the Quantity per UnitPrice by CustomerID for the top 3 Countries
Hint: First we need to find top-3 countries based on revenue, then create scater plot between Quantity and Unitprice for each country separately

## The below exercises (81-90) required to use FMCG_Company_Data_2019.csv file

### 81. Import the dataset FMCG_Company_Data_2019.csv and assign it to a variable called company_data

### 82. Create line chart for Total Revenue of all months with following properties
- X label name = Month
- Y label name = Total Revenue

### 83. Create line chart for Total Units of all months with following properties
- X label name = Month
- Y label name = Total Units
- Line Style dotted and Line-color should be red
- Show legend at the lower right location.

### 84. Read all product sales data (Facecream, FaceWash, Toothpaste, Soap, Shampo, Moisturizer) and show it  using a multiline plot
- Display the number of units sold per month for each product using multiline plots. (i.e., Separate Plotline for each product ).

### 85. Create Bar Chart for soap of all months and Save the chart in folder

### 86. Create Stacked Bar Chart for Soap, Shampo, ToothPaste for each month
The bar chart should display the number of units sold per month for each product. Add a separate bar for each product in the same chart.

### 87. Create Histogram for Total Revenue

### 88. Calculate total sales data (quantity) for 2019 for each product and show it using a Pie chart. Understand percentage contribution from each product

### 89. Create line plots for Soap & Facewash of all months in a single plot using Subplot

### 90. Create Box Plot for Total Profit variable